const QUESTION_BANK = [
  {
    id: 1,
    question: "What best describes GitHub Copilot?",
    choices: [
      "A static code formatter",
      "An AI pair programmer that suggests code",
      "A version control system",
      "A package manager",
    ],
    answerIndex: 1,
    explanation: "GitHub Copilot provides AI-generated code suggestions inside your editor.",
  },
  {
    id: 2,
    question: "Copilot suggestions are primarily based on which inputs?",
    choices: [
      "Only the file name",
      "Surrounding code and comments in context",
      "The last Git commit message",
      "A predefined template library only",
    ],
    answerIndex: 1,
    explanation: "Copilot builds prompts from nearby code, comments, and related context.",
  },
  {
    id: 3,
    question: "Which is one of Microsoft and GitHub's responsible AI principles?",
    choices: ["Monetization", "Fairness", "Speed", "Gamification"],
    answerIndex: 1,
    explanation: "Fairness is one of the six responsible AI principles.",
  },
  {
    id: 4,
    question: "Which is a common risk when using generative AI tools?",
    choices: [
      "Guaranteed correctness",
      "Hallucinated or incorrect outputs",
      "Automatic licensing compliance",
      "Perfect security hardening",
    ],
    answerIndex: 1,
    explanation: "Generative AI can produce plausible but incorrect results.",
  },
  {
    id: 5,
    question: "What is the best way to mitigate risks from Copilot suggestions?",
    choices: [
      "Accept suggestions without review",
      "Disable all comments in code",
      "Validate outputs with testing and review",
      "Avoid using any IDE extensions",
    ],
    answerIndex: 2,
    explanation: "You should validate AI output through review and tests.",
  },
  {
    id: 6,
    question: "Who is responsible for the final code when using Copilot?",
    choices: ["The AI model", "GitHub", "The developer", "The IDE vendor"],
    answerIndex: 2,
    explanation: "Developers remain responsible for the code they accept.",
  },
  {
    id: 7,
    question: "Which practice best protects sensitive information when using Copilot?",
    choices: [
      "Paste secrets into prompts to speed up results",
      "Use content exclusions and avoid sharing secrets",
      "Rely on Copilot to filter all secrets automatically",
      "Store secrets in comments for context",
    ],
    answerIndex: 1,
    explanation: "Avoid including secrets and configure content exclusions.",
  },
  {
    id: 8,
    question: "Which statement reflects ethical and responsible AI usage?",
    choices: [
      "Use AI outputs without oversight",
      "Ignore security warnings to move faster",
      "Review outputs for bias and safety",
      "Prefer the longest suggestions by default",
    ],
    answerIndex: 2,
    explanation: "Responsible use includes reviewing for bias, safety, and accuracy.",
  },
  {
    id: 9,
    question: "Which limitation is important to remember about Copilot?",
    choices: [
      "It always generates secure code",
      "It may suggest incorrect or insecure code",
      "It can replace code review",
      "It only works in the browser",
    ],
    answerIndex: 1,
    explanation: "Copilot suggestions are not guaranteed to be correct or secure.",
  },
  {
    id: 10,
    question: "How should Copilot be used for learning?",
    choices: [
      "As a substitute for documentation",
      "As a helper with verification",
      "As the only source of truth",
      "As a replacement for tests",
    ],
    answerIndex: 1,
    explanation: "Use Copilot as a helper and verify with trusted sources.",
  },
  {
    id: 11,
    question: "Which activity is part of validating AI output?",
    choices: [
      "Skipping tests to save time",
      "Running tests and reviewing logic",
      "Assuming the AI output is correct",
      "Deleting unit tests",
    ],
    answerIndex: 1,
    explanation: "Validation includes testing and reviewing the code.",
  },
  {
    id: 12,
    question: "If a Copilot suggestion violates policy, what should you do?",
    choices: [
      "Accept it to keep momentum",
      "Discard it and follow policy",
      "Hide it in a comment",
      "Commit it to a private branch",
    ],
    answerIndex: 1,
    explanation: "Policy compliance takes priority over speed.",
  },
  {
    id: 13,
    question: "Responsible AI emphasizes which goal?",
    choices: [
      "Speed only",
      "Fair, transparent, and accountable use",
      "Automatic code ownership transfer",
      "Eliminating human oversight",
    ],
    answerIndex: 1,
    explanation: "Responsible AI focuses on fairness, transparency, and accountability.",
  },
  {
    id: 14,
    question: "What is a potential harm from AI bias in code suggestions?",
    choices: [
      "Improved accuracy",
      "Unfair or exclusionary outcomes",
      "Guaranteed privacy",
      "Perfect test coverage",
    ],
    answerIndex: 1,
    explanation: "Bias can lead to unfair or exclusionary outcomes.",
  },
  {
    id: 15,
    question: "What does 'hallucination' mean in AI outputs?",
    choices: [
      "Outputs that are guaranteed correct",
      "Outputs that are plausible but incorrect",
      "Outputs that include citations",
      "Outputs that compile without errors",
    ],
    answerIndex: 1,
    explanation: "Hallucinations are plausible but incorrect outputs.",
  },
  {
    id: 16,
    question: "Which prompt is most responsible when using Copilot?",
    choices: [
      "Include production secrets to be precise",
      "Provide clear context without sensitive data",
      "Use vague prompts to save time",
      "Ask for proprietary code from competitors",
    ],
    answerIndex: 1,
    explanation: "Provide clear, safe context without sensitive information.",
  },
  {
    id: 17,
    question: "If you are unsure about a suggestion, you should:",
    choices: [
      "Accept it to keep flow",
      "Validate it or ask for clarification",
      "Ignore all suggestions permanently",
      "Disable your IDE",
    ],
    answerIndex: 1,
    explanation: "Verify correctness and ask for clarification if needed.",
  },
  {
    id: 18,
    question: "Copilot should not replace which critical practice?",
    choices: ["Human judgment", "Syntax highlighting", "Auto-save", "Search"],
    answerIndex: 0,
    explanation: "Human judgment is essential for responsible AI use.",
  },
  {
    id: 19,
    question: "Which statement is true about code ownership with Copilot?",
    choices: [
      "Copilot owns the generated code",
      "The developer owns and is responsible for accepted code",
      "Ownership transfers to GitHub automatically",
      "Ownership is always shared with the model",
    ],
    answerIndex: 1,
    explanation: "Developers are responsible for the code they use.",
  },
  {
    id: 20,
    question: "What is a good security practice when using AI suggestions?",
    choices: [
      "Skip security review to save time",
      "Review code for vulnerabilities and run tests",
      "Assume the code is safe",
      "Disable linters",
    ],
    answerIndex: 1,
    explanation: "Security review and testing are essential.",
  },
  {
    id: 21,
    question: "Which Copilot plans are covered in the learning path?",
    choices: [
      "Home, Pro, Ultimate",
      "Individuals, Business, Enterprise",
      "Starter, Plus, Max",
      "Basic, Standard, Premium",
    ],
    answerIndex: 1,
    explanation: "The course discusses Individuals, Business, and Enterprise plans.",
  },
  {
    id: 22,
    question: "Which plan type emphasizes organization-wide management?",
    choices: ["Individuals", "Business or Enterprise", "Student only", "Trial only"],
    answerIndex: 1,
    explanation: "Business and Enterprise plans support org-level management.",
  },
  {
    id: 23,
    question: "A common setup step for Copilot in an IDE is to:",
    choices: [
      "Install the Copilot extension and sign in",
      "Disable code completion entirely",
      "Remove Git from the system",
      "Create a new repository",
    ],
    answerIndex: 0,
    explanation: "Setup typically includes installing the extension and signing in.",
  },
  {
    id: 24,
    question: "Copilot is available in which environments?",
    choices: [
      "Only the browser",
      "Only Visual Studio Code",
      "IDE, Chat, GitHub.com, and command line",
      "Only command line",
    ],
    answerIndex: 2,
    explanation: "Copilot works across IDEs, Chat, GitHub.com, and the CLI.",
  },
  {
    id: 25,
    question: "Inline suggestions in an IDE are triggered by:",
    choices: [
      "Only running tests",
      "Typing code and comments",
      "Closing the editor",
      "Publishing a release",
    ],
    answerIndex: 1,
    explanation: "Typing and context trigger inline suggestions.",
  },
  {
    id: 26,
    question: "GitHub Copilot Chat is best used for:",
    choices: [
      "Natural language questions and code explanations",
      "Replacing all code reviews",
      "Managing Git history",
      "Building release pipelines",
    ],
    answerIndex: 0,
    explanation: "Chat is designed for conversational help and explanations.",
  },
  {
    id: 27,
    question: "The Copilot CLI is intended to:",
    choices: [
      "Generate shell commands from natural language",
      "Run SQL migrations automatically",
      "Replace your terminal",
      "Deploy applications by itself",
    ],
    answerIndex: 0,
    explanation: "Copilot CLI helps turn natural language into commands.",
  },
  {
    id: 28,
    question: "Content exclusions are used to:",
    choices: [
      "Increase suggestion verbosity",
      "Prevent specific files or repos from being used",
      "Force all suggestions to be accepted",
      "Turn off chat entirely",
    ],
    answerIndex: 1,
    explanation: "Exclusions prevent specific content from being used.",
  },
  {
    id: 29,
    question: "A first troubleshooting step for Copilot is to:",
    choices: [
      "Delete all source code",
      "Verify extension is enabled and you are signed in",
      "Disable the internet",
      "Remove your IDE",
    ],
    answerIndex: 1,
    explanation: "Check that the extension is enabled and signed in.",
  },
  {
    id: 30,
    question: "Which module covers Copilot across IDE, Chat, GitHub.com, and CLI?",
    choices: [
      "Responsible AI with GitHub Copilot",
      "GitHub Copilot Across Environments",
      "Introduction to Copilot Spaces",
      "Develop unit tests using GitHub Copilot tools",
    ],
    answerIndex: 1,
    explanation: "The learning path includes a module on Copilot across environments.",
  },
  {
    id: 31,
    question: "What improves Copilot suggestion quality?",
    choices: [
      "Removing all comments",
      "Providing clear context and intent",
      "Turning off linting",
      "Avoiding descriptive names",
    ],
    answerIndex: 1,
    explanation: "Clear context and intent help the model produce better output.",
  },
  {
    id: 32,
    question: "Copilot can suggest:",
    choices: [
      "Only single-line completions",
      "Entire functions and blocks of code",
      "Only comments",
      "Only test data",
    ],
    answerIndex: 1,
    explanation: "Copilot can suggest multi-line code and entire functions.",
  },
  {
    id: 33,
    question: "Using Copilot responsibly in an organization includes:",
    choices: [
      "Ignoring organization policies",
      "Following organization policies and guidance",
      "Sharing secrets to improve results",
      "Bypassing security reviews",
    ],
    answerIndex: 1,
    explanation: "Follow organizational policies and guidance.",
  },
  {
    id: 34,
    question: "Which statement about Copilot plan features is true?",
    choices: [
      "All plans offer identical management controls",
      "Business/Enterprise include additional management capabilities",
      "Individual plan has more org controls than Enterprise",
      "Plans are not differentiated",
    ],
    answerIndex: 1,
    explanation: "Business and Enterprise include additional controls.",
  },
  {
    id: 35,
    question: "Organization-wide content exclusions can be configured in:",
    choices: [
      "Operating system settings",
      "Copilot organization settings",
      "The Git history",
      "IDE theme settings",
    ],
    answerIndex: 1,
    explanation: "Content exclusions are managed in Copilot settings for the org.",
  },
  {
    id: 36,
    question: "Copilot requires network access primarily because:",
    choices: [
      "It runs only on a local model",
      "Suggestions are generated by an online service",
      "It only works offline",
      "It uses no external services",
    ],
    answerIndex: 1,
    explanation: "Copilot sends prompts to an online service for completion.",
  },
  {
    id: 37,
    question: "On GitHub.com, Copilot can help with:",
    choices: [
      "Pull request assistance and review workflows",
      "Replacing git push",
      "Installing operating system updates",
      "Managing SSH keys only",
    ],
    answerIndex: 0,
    explanation: "Copilot can assist with PR tasks on GitHub.com.",
  },
  {
    id: 38,
    question: "Disabling matching public code helps:",
    choices: [
      "Increase suggestion length",
      "Reduce suggestions similar to public code",
      "Disable Copilot entirely",
      "Force suggestions to be identical to public code",
    ],
    answerIndex: 1,
    explanation: "It reduces the chance of suggestions matching public code.",
  },
  {
    id: 39,
    question: "Which topic is covered under management and customization?",
    choices: [
      "Contractual protections and public code matching",
      "GPU overclocking",
      "Mobile deployment pipelines",
      "Kernel patching",
    ],
    answerIndex: 0,
    explanation: "The module covers contractual protections and public code matching.",
  },
  {
    id: 40,
    question: "Duplication detection is primarily related to:",
    choices: [
      "Measuring file size",
      "Detecting similarities with public code",
      "Optimizing build time",
      "Tracking open issues",
    ],
    answerIndex: 1,
    explanation: "Duplication detection flags suggestions similar to public code.",
  },
  {
    id: 41,
    question: "Which elements make a prompt more effective?",
    choices: [
      "Clear goal, context, and constraints",
      "Only a single vague sentence",
      "No information about inputs or outputs",
      "Avoiding any details about language",
    ],
    answerIndex: 0,
    explanation: "Effective prompts include goals, context, and constraints.",
  },
  {
    id: 42,
    question: "Zero-shot prompting means:",
    choices: [
      "Providing no examples",
      "Providing many examples",
      "Only using code snippets",
      "Avoiding any constraints",
    ],
    answerIndex: 0,
    explanation: "Zero-shot uses no examples, only instructions.",
  },
  {
    id: 43,
    question: "Few-shot prompting means:",
    choices: [
      "Using one or more examples",
      "Using no examples at all",
      "Only pasting test results",
      "Avoiding context",
    ],
    answerIndex: 0,
    explanation: "Few-shot includes examples to guide the model.",
  },
  {
    id: 44,
    question: "A best practice for prompts is to:",
    choices: [
      "Be as specific as possible",
      "Avoid stating constraints",
      "Omit desired language",
      "Use contradictory instructions",
    ],
    answerIndex: 0,
    explanation: "Specific prompts help the model generate more accurate output.",
  },
  {
    id: 45,
    question: "Inline Copilot suggestions are often guided by:",
    choices: [
      "Comments that describe intent",
      "The OS file permissions only",
      "IDE themes",
      "Git tags",
    ],
    answerIndex: 0,
    explanation: "Comments describing intent help guide suggestions.",
  },
  {
    id: 46,
    question: "Chat history can affect responses by:",
    choices: [
      "Providing context for follow-up prompts",
      "Changing your repository history",
      "Disabling linting",
      "Modifying dependency versions",
    ],
    answerIndex: 0,
    explanation: "Chat history provides context for subsequent responses.",
  },
  {
    id: 47,
    question: "Adding constraints in a prompt helps Copilot:",
    choices: [
      "Ignore your request",
      "Generate output that matches style and requirements",
      "Increase hallucinations",
      "Avoid code generation",
    ],
    answerIndex: 1,
    explanation: "Constraints help align output with requirements.",
  },
  {
    id: 48,
    question: "Which prompt improves test generation quality?",
    choices: [
      "“Write tests” with no context",
      "“Write unit tests for this function with edge cases”",
      "“Ignore edge cases”",
      "“Do not use assertions”",
    ],
    answerIndex: 1,
    explanation: "Specific prompts yield more relevant tests.",
  },
  {
    id: 49,
    question: "Iterative prompting means:",
    choices: [
      "Never changing your prompt",
      "Refining prompts based on results",
      "Avoiding follow-up questions",
      "Only using default suggestions",
    ],
    answerIndex: 1,
    explanation: "Iterative prompting refines outputs over multiple steps.",
  },
  {
    id: 50,
    question: "Providing a minimal reproducible snippet helps because it:",
    choices: [
      "Adds irrelevant context",
      "Keeps the prompt focused and clear",
      "Removes all context",
      "Only works for markdown",
    ],
    answerIndex: 1,
    explanation: "Focused context improves relevance and accuracy.",
  },
  {
    id: 51,
    question: "The Copilot prompt process flow generally includes:",
    choices: [
      "Context collection, model request, post-processing",
      "Compiling the project before prompting",
      "Running deployment pipelines",
      "Publishing to npm",
    ],
    answerIndex: 0,
    explanation: "Copilot collects context, sends it to the model, then post-processes.",
  },
  {
    id: 52,
    question: "Why does Copilot apply filtering and post-processing?",
    choices: [
      "To remove irrelevant or unsafe suggestions",
      "To slow down the editor",
      "To alter your git history",
      "To avoid any code suggestions",
    ],
    answerIndex: 0,
    explanation: "Filtering helps remove unsafe or low-quality outputs.",
  },
  {
    id: 53,
    question: "A limitation of LLMs is that they:",
    choices: [
      "Are deterministic compilers",
      "Are probabilistic and can be wrong",
      "Always know your private repo contents",
      "Guarantee security compliance",
    ],
    answerIndex: 1,
    explanation: "LLMs are probabilistic and can make mistakes.",
  },
  {
    id: 54,
    question: "If a response is inaccurate, a good next step is to:",
    choices: [
      "Ask a clarifying follow-up prompt",
      "Assume all future answers are correct",
      "Disable all code reviews",
      "Ignore the issue",
    ],
    answerIndex: 0,
    explanation: "Use follow-up prompts to refine the response.",
  },
  {
    id: 55,
    question: "Which prompt is best for consistent formatting?",
    choices: [
      "“Generate code”",
      "“Generate code in TypeScript using ESLint rules below”",
      "“Do whatever you want”",
      "“Use any language”",
    ],
    answerIndex: 1,
    explanation: "Specific constraints guide consistent formatting.",
  },
  {
    id: 56,
    question: "Natural language prompts are useful because they:",
    choices: [
      "Disable code generation",
      "Describe intent in a human-friendly way",
      "Only work in Python",
      "Remove the need for tests",
    ],
    answerIndex: 1,
    explanation: "Natural language helps describe intent clearly.",
  },
  {
    id: 57,
    question: "Placeholders in prompts help by:",
    choices: [
      "Avoiding any requirements",
      "Signaling expected structure or format",
      "Forcing compilation errors",
      "Making prompts shorter but less clear",
    ],
    answerIndex: 1,
    explanation: "Placeholders convey structure and expectations.",
  },
  {
    id: 58,
    question: "Ambiguous prompts often lead to:",
    choices: [
      "More precise answers",
      "Unpredictable or irrelevant output",
      "Perfect solutions",
      "Guaranteed correctness",
    ],
    answerIndex: 1,
    explanation: "Ambiguity can reduce relevance and accuracy.",
  },
  {
    id: 59,
    question: "Copilot Chat can help by:",
    choices: [
      "Explaining unfamiliar code",
      "Running production deployments",
      "Editing git history",
      "Automating HR workflows",
    ],
    answerIndex: 0,
    explanation: "Chat can explain code and answer questions.",
  },
  {
    id: 60,
    question: "When learning a new library, you should:",
    choices: [
      "Use Copilot as a helper and verify with docs",
      "Trust Copilot as the only source",
      "Avoid any prompts",
      "Disable unit tests",
    ],
    answerIndex: 0,
    explanation: "Use Copilot as a helper and verify with documentation.",
  },
  {
    id: 61,
    question: "Copilot’s data flow starts with:",
    choices: [
      "Collecting context to build a prompt",
      "Publishing to a package registry",
      "Creating a new repository",
      "Generating a release note",
    ],
    answerIndex: 0,
    explanation: "Copilot builds a prompt from available context.",
  },
  {
    id: 62,
    question: "Which content can be part of the prompt context?",
    choices: [
      "Only the README",
      "Surrounding code, comments, and related files",
      "Only commit history",
      "Only test reports",
    ],
    answerIndex: 1,
    explanation: "Context may include nearby code and related files.",
  },
  {
    id: 63,
    question: "Post-processing helps by:",
    choices: [
      "Filtering or ranking suggestions",
      "Changing your compiler settings",
      "Deleting files",
      "Running tests automatically",
    ],
    answerIndex: 0,
    explanation: "Post-processing helps refine the suggestions shown.",
  },
  {
    id: 64,
    question: "Large language models are best described as:",
    choices: [
      "Rule-based compilers",
      "Probabilistic models that predict text",
      "Static analyzers",
      "Package installers",
    ],
    answerIndex: 1,
    explanation: "LLMs predict likely text based on context.",
  },
  {
    id: 65,
    question: "Why might a Copilot suggestion fail to compile?",
    choices: [
      "It is always correct",
      "It can be incomplete or incorrect",
      "It disables the compiler",
      "It only generates comments",
    ],
    answerIndex: 1,
    explanation: "Suggestions can be incomplete or inaccurate.",
  },
  {
    id: 66,
    question: "Which tool is best for asking 'why' about a code block?",
    choices: [
      "GitHub Copilot Chat",
      "A package manager",
      "A linter",
      "A build system",
    ],
    answerIndex: 0,
    explanation: "Copilot Chat can explain code and reasoning.",
  },
  {
    id: 67,
    question: "Copilot can assist with tests, but you must:",
    choices: [
      "Skip running them",
      "Validate that tests are correct and pass",
      "Remove assertions",
      "Only use generated tests",
    ],
    answerIndex: 1,
    explanation: "Generated tests still need validation.",
  },
  {
    id: 68,
    question: "The suggestion lifecycle typically ends with:",
    choices: [
      "Automatic code deployment",
      "Displaying suggestions in the editor",
      "Publishing to GitHub Pages",
      "Archiving the repository",
    ],
    answerIndex: 1,
    explanation: "Suggestions are displayed for the developer to review.",
  },
  {
    id: 69,
    question: "If key context is missing, Copilot will likely:",
    choices: [
      "Provide more accurate suggestions",
      "Provide less relevant suggestions",
      "Disable the IDE",
      "Generate only comments",
    ],
    answerIndex: 1,
    explanation: "Missing context reduces suggestion relevance.",
  },
  {
    id: 70,
    question: "Why do context windows matter?",
    choices: [
      "They define how much information the model can consider",
      "They set your IDE theme",
      "They control Git history depth",
      "They only affect compilation speed",
    ],
    answerIndex: 0,
    explanation: "Models can only consider a limited amount of context.",
  },
  {
    id: 71,
    question: "Which practice protects sensitive data?",
    choices: [
      "Sharing secrets in prompts",
      "Applying content exclusions for sensitive files",
      "Embedding secrets in comments",
      "Posting secrets in issues",
    ],
    answerIndex: 1,
    explanation: "Use content exclusions and avoid including secrets.",
  },
  {
    id: 72,
    question: "Why avoid including secrets in prompts?",
    choices: [
      "It slows down the IDE",
      "It can expose sensitive information",
      "It improves accuracy",
      "It is required for Copilot to work",
    ],
    answerIndex: 1,
    explanation: "Sharing secrets can expose sensitive data.",
  },
  {
    id: 73,
    question: "Content exclusions ensure that:",
    choices: [
      "Copilot ignores specified files or repos",
      "Copilot suggests longer code",
      "Copilot disables chat only",
      "Copilot uses only tests",
    ],
    answerIndex: 0,
    explanation: "Excluded content is not used to generate suggestions.",
  },
  {
    id: 74,
    question: "Which action improves relevance in Chat?",
    choices: [
      "Reference specific files or code blocks",
      "Ask a vague question",
      "Avoid mentioning the goal",
      "Remove all context",
    ],
    answerIndex: 0,
    explanation: "Specific context improves Chat relevance.",
  },
  {
    id: 75,
    question: "When using Copilot Chat, selecting a code block:",
    choices: [
      "Removes it from your project",
      "Provides focused context for the prompt",
      "Disables suggestions",
      "Changes formatting settings",
    ],
    answerIndex: 1,
    explanation: "Selected code helps the model focus on relevant context.",
  },
  {
    id: 76,
    question: "A good prompt for refactoring includes:",
    choices: [
      "No constraints or goals",
      "Specific goals, constraints, and style guidance",
      "Only a file path",
      "Only a summary without code",
    ],
    answerIndex: 1,
    explanation: "Clear goals and constraints improve refactoring output.",
  },
  {
    id: 77,
    question: "Which request best supports reliable generation?",
    choices: [
      "Provide clear inputs and expected outputs",
      "Provide no examples",
      "Ask for any possible solution",
      "Avoid mentioning edge cases",
    ],
    answerIndex: 0,
    explanation: "Inputs and expected outputs guide reliable generation.",
  },
  {
    id: 78,
    question: "Copilot can explain a snippet by:",
    choices: [
      "Summarizing its purpose in natural language",
      "Running the code in production",
      "Changing commit history",
      "Publishing a package",
    ],
    answerIndex: 0,
    explanation: "Chat can explain code in natural language.",
  },
  {
    id: 79,
    question: "Providing sample I/O is most helpful when:",
    choices: [
      "Writing a function with a clear contract",
      "Renaming files",
      "Updating git config",
      "Changing IDE themes",
    ],
    answerIndex: 0,
    explanation: "Sample I/O clarifies the expected function behavior.",
  },
  {
    id: 80,
    question: "Overfitting to a wrong example can cause:",
    choices: [
      "Incorrect output aligned to bad constraints",
      "Always correct output",
      "No output at all",
      "Automatic fixes",
    ],
    answerIndex: 0,
    explanation: "Bad examples can bias the model toward incorrect results.",
  },
  {
    id: 81,
    question: "Inline Copilot suggestions typically appear as:",
    choices: [
      "Ghost text in the editor",
      "Terminal warnings",
      "Build logs",
      "Git tags",
    ],
    answerIndex: 0,
    explanation: "Inline suggestions appear as ghost text in the editor.",
  },
  {
    id: 82,
    question: "Accepting an inline suggestion usually involves:",
    choices: [
      "Using the IDE’s accept suggestion command",
      "Running a build",
      "Closing the file",
      "Editing Git config",
    ],
    answerIndex: 0,
    explanation: "The IDE provides a command to accept suggestions.",
  },
  {
    id: 83,
    question: "Copilot Chat is accessible directly from:",
    choices: [
      "The IDE interface",
      "The operating system login screen",
      "The BIOS",
      "A hardware debugger",
    ],
    answerIndex: 0,
    explanation: "Copilot Chat is integrated into the IDE interface.",
  },
  {
    id: 84,
    question: "The Copilot CLI is most useful for:",
    choices: [
      "Explaining shell commands or generating them",
      "Replacing GitHub Actions",
      "Managing IDE themes",
      "Compiling code",
    ],
    answerIndex: 0,
    explanation: "It helps explain or generate commands from natural language.",
  },
  {
    id: 85,
    question: "Copilot on GitHub.com can assist with:",
    choices: [
      "Pull request summaries and reviews",
      "Replacing git clone",
      "Changing account passwords",
      "Managing DNS",
    ],
    answerIndex: 0,
    explanation: "Copilot can assist with PR tasks on GitHub.com.",
  },
  {
    id: 86,
    question: "Copilot Chat can help with:",
    choices: [
      "Generating and refactoring code",
      "Changing OS kernel settings",
      "Editing git history",
      "Installing GPU drivers",
    ],
    answerIndex: 0,
    explanation: "Chat can generate and refactor code with guidance.",
  },
  {
    id: 87,
    question: "Copilot Spaces are designed to:",
    choices: [
      "Provide curated context for grounded answers",
      "Replace issue trackers",
      "Host CI pipelines",
      "Manage container images",
    ],
    answerIndex: 0,
    explanation: "Spaces provide shared context to improve response quality.",
  },
  {
    id: 88,
    question: "A Copilot Space can include:",
    choices: [
      "Repositories and documentation",
      "Only emojis",
      "Only build logs",
      "Only runtime metrics",
    ],
    answerIndex: 0,
    explanation: "Spaces can include repos and docs for grounding.",
  },
  {
    id: 89,
    question: "Space governance helps with:",
    choices: [
      "Controlling access and sharing",
      "Changing IDE fonts",
      "Deleting repositories",
      "Forcing suggestions",
    ],
    answerIndex: 0,
    explanation: "Governance controls sharing and access policies.",
  },
  {
    id: 90,
    question: "Copilot used across environments uses:",
    choices: [
      "Your GitHub account authentication",
      "A local-only token",
      "No authentication",
      "BIOS credentials",
    ],
    answerIndex: 0,
    explanation: "Copilot access is tied to your GitHub account.",
  },
  {
    id: 91,
    question: "When using the Copilot CLI, you should:",
    choices: [
      "Review commands before executing",
      "Run every command automatically",
      "Disable shell history",
      "Skip validation",
    ],
    answerIndex: 0,
    explanation: "Always review generated commands before executing them.",
  },
  {
    id: 92,
    question: "Copilot can help generate:",
    choices: [
      "Documentation and code comments",
      "Hardware drivers only",
      "BIOS settings",
      "SSL certificates",
    ],
    answerIndex: 0,
    explanation: "Copilot can assist with documentation and comments.",
  },
  {
    id: 93,
    question: "Copilot can help modernize legacy code by:",
    choices: [
      "Suggesting updated patterns or APIs",
      "Automatically deploying to production",
      "Deleting old files",
      "Changing repository ownership",
    ],
    answerIndex: 0,
    explanation: "Copilot can suggest modern patterns or API usage.",
  },
  {
    id: 94,
    question: "Copilot can help create sample data by:",
    choices: [
      "Generating representative records",
      "Deleting databases",
      "Changing OS permissions",
      "Replacing backups",
    ],
    answerIndex: 0,
    explanation: "Copilot can generate representative sample data.",
  },
  {
    id: 95,
    question: "Copilot can help identify edge cases by:",
    choices: [
      "Suggesting additional test scenarios",
      "Removing tests",
      "Skipping validations",
      "Disabling linting",
    ],
    answerIndex: 0,
    explanation: "Copilot can suggest edge cases for testing.",
  },
  {
    id: 96,
    question: "Using Copilot can reduce context switching because it:",
    choices: [
      "Answers questions directly in the IDE",
      "Replaces documentation",
      "Removes the need for any code",
      "Disables code reviews",
    ],
    answerIndex: 0,
    explanation: "Copilot can answer questions in context within the IDE.",
  },
  {
    id: 97,
    question: "Copilot can assist with refactoring by:",
    choices: [
      "Suggesting code improvements",
      "Changing git history",
      "Deleting branches",
      "Managing user accounts",
    ],
    answerIndex: 0,
    explanation: "Copilot can suggest refactoring improvements.",
  },
  {
    id: 98,
    question: "Copilot can suggest performance improvements, but you must:",
    choices: [
      "Validate with profiling and tests",
      "Accept automatically",
      "Disable benchmarks",
      "Skip review",
    ],
    answerIndex: 0,
    explanation: "Performance suggestions still require validation.",
  },
  {
    id: 99,
    question: "Copilot can suggest security improvements, but you should:",
    choices: [
      "Review and validate them",
      "Disable security scanning",
      "Assume they are perfect",
      "Avoid testing",
    ],
    answerIndex: 0,
    explanation: "Security recommendations need review and validation.",
  },
  {
    id: 100,
    question: "Copilot can help create tests by:",
    choices: [
      "Generating unit test scaffolding",
      "Running tests automatically",
      "Replacing test frameworks",
      "Deleting existing tests",
    ],
    answerIndex: 0,
    explanation: "Copilot can generate test scaffolding and cases.",
  },
  {
    id: 101,
    question: "The Generate Tests smart action helps you:",
    choices: [
      "Create unit tests from code selection",
      "Delete test files",
      "Remove code comments",
      "Change editor settings",
    ],
    answerIndex: 0,
    explanation: "Generate Tests helps create tests based on selected code.",
  },
  {
    id: 102,
    question: "Inline Chat can be used to:",
    choices: [
      "Generate tests for a selected function",
      "Replace your compiler",
      "Manage git merges",
      "Change OS permissions",
    ],
    answerIndex: 0,
    explanation: "Inline Chat can generate tests for selected code.",
  },
  {
    id: 103,
    question: "Chat view modes in the testing module emphasize:",
    choices: [
      "Using chat to create tests in different contexts",
      "Avoiding tests entirely",
      "Only manual testing",
      "Disabling code completion",
    ],
    answerIndex: 0,
    explanation: "Chat view modes show how to use chat for test creation.",
  },
  {
    id: 104,
    question: "A good unit test includes:",
    choices: [
      "Assertions that check expected behavior",
      "Only print statements",
      "No expected outcomes",
      "Random outputs",
    ],
    answerIndex: 0,
    explanation: "Assertions are essential to validate behavior.",
  },
  {
    id: 105,
    question: "High-quality tests should cover:",
    choices: [
      "Happy path only",
      "Edge cases and error conditions",
      "Only trivial cases",
      "Only manual steps",
    ],
    answerIndex: 1,
    explanation: "Tests should include edge cases and errors.",
  },
  {
    id: 106,
    question: "When generating tests with Copilot, you should:",
    choices: [
      "Provide function signatures and expected behavior",
      "Avoid describing behavior",
      "Remove context",
      "Skip assertions",
    ],
    answerIndex: 0,
    explanation: "Context and expectations improve test quality.",
  },
  {
    id: 107,
    question: "Copilot-generated tests should be:",
    choices: [
      "Reviewed and validated",
      "Committed without review",
      "Used as the only tests",
      "Left unrun",
    ],
    answerIndex: 0,
    explanation: "Generated tests should be reviewed and validated.",
  },
  {
    id: 108,
    question: "Copilot can help with test frameworks by:",
    choices: [
      "Suggesting idiomatic structure for the framework",
      "Replacing the framework",
      "Disabling test runners",
      "Deleting configuration files",
    ],
    answerIndex: 0,
    explanation: "Copilot can suggest framework-appropriate test structure.",
  },
  {
    id: 109,
    question: "When generating tests, include inputs and outputs to:",
    choices: [
      "Clarify expected behavior",
      "Reduce clarity",
      "Remove context",
      "Confuse the model",
    ],
    answerIndex: 0,
    explanation: "Inputs and outputs clarify expectations.",
  },
  {
    id: 110,
    question: "Tests should be deterministic to:",
    choices: [
      "Reduce flaky failures",
      "Increase randomness",
      "Avoid assertions",
      "Hide bugs",
    ],
    answerIndex: 0,
    explanation: "Deterministic tests reduce flaky failures.",
  },
  {
    id: 111,
    question: "Copilot can assist with test refactoring by:",
    choices: [
      "Suggesting clearer structure and naming",
      "Removing all tests",
      "Changing licensing",
      "Deleting fixtures",
    ],
    answerIndex: 0,
    explanation: "Copilot can suggest clearer test structure.",
  },
  {
    id: 112,
    question: "A smart way to create tests is to:",
    choices: [
      "Select the function and use Generate Tests",
      "Write tests with no context",
      "Skip testing",
      "Only use manual testing",
    ],
    answerIndex: 0,
    explanation: "Generate Tests uses selected code as context.",
  },
  {
    id: 113,
    question: "When tests fail, Copilot Chat can help by:",
    choices: [
      "Explaining potential causes",
      "Deleting failing tests",
      "Ignoring the failures",
      "Changing git history",
    ],
    answerIndex: 0,
    explanation: "Chat can help reason about failures.",
  },
  {
    id: 114,
    question: "Unit testing contributes to:",
    choices: [
      "Code quality and reliability",
      "Avoiding documentation",
      "Removing code reviews",
      "Fewer validations",
    ],
    answerIndex: 0,
    explanation: "Testing improves quality and reliability.",
  },
  {
    id: 115,
    question: "Copilot can suggest mocking strategies, but you must:",
    choices: [
      "Validate they match your test goals",
      "Accept them blindly",
      "Avoid using mocks",
      "Delete dependencies",
    ],
    answerIndex: 0,
    explanation: "Mocking strategies must align with test goals.",
  },
  {
    id: 116,
    question: "Integration tests typically validate:",
    choices: [
      "Interactions between components",
      "Only a single function",
      "Just the UI theme",
      "Only lint rules",
    ],
    answerIndex: 0,
    explanation: "Integration tests validate component interactions.",
  },
  {
    id: 117,
    question: "Boundary testing often focuses on:",
    choices: [
      "Extreme or edge values",
      "Random formatting",
      "Only happy paths",
      "Changing IDE fonts",
    ],
    answerIndex: 0,
    explanation: "Boundary testing uses extreme or edge values.",
  },
  {
    id: 118,
    question: "Negative tests are used to:",
    choices: [
      "Validate handling of invalid inputs",
      "Avoid error scenarios",
      "Only test the happy path",
      "Remove error handling",
    ],
    answerIndex: 0,
    explanation: "Negative tests validate invalid input handling.",
  },
  {
    id: 119,
    question: "After fixing a bug, tests should:",
    choices: [
      "Include a regression test for the bug",
      "Remove existing tests",
      "Be skipped",
      "Only test unrelated features",
    ],
    answerIndex: 0,
    explanation: "Regression tests prevent the bug from recurring.",
  },
  {
    id: 120,
    question: "Readable tests improve:",
    choices: [
      "Maintainability and collaboration",
      "Runtime memory usage only",
      "Compilation speed only",
      "None of the above",
    ],
    answerIndex: 0,
    explanation: "Readable tests are easier to maintain and collaborate on.",
  },
  {
    id: 121,
    question: "Content exclusions can be configured at:",
    choices: [
      "Repository or organization level",
      "Only the operating system level",
      "Only the hardware level",
      "Only in markdown files",
    ],
    answerIndex: 0,
    explanation: "Exclusions can be set at repo or org level.",
  },
  {
    id: 122,
    question: "Excluded files are:",
    choices: [
      "Ignored by Copilot for suggestions",
      "Always used for suggestions",
      "Converted to markdown",
      "Deleted automatically",
    ],
    answerIndex: 0,
    explanation: "Excluded files are not used for suggestions.",
  },
  {
    id: 123,
    question: "Disabling matching public code is primarily about:",
    choices: [
      "Reducing similarity to public code in suggestions",
      "Increasing build speed",
      "Removing Copilot Chat",
      "Enabling more suggestions",
    ],
    answerIndex: 0,
    explanation: "It reduces suggestions similar to public code.",
  },
  {
    id: 124,
    question: "Contractual protections are discussed in the context of:",
    choices: [
      "Copilot plans and management features",
      "Package managers",
      "Git branch strategies",
      "UI design patterns",
    ],
    answerIndex: 0,
    explanation: "Contractual protections are part of management considerations.",
  },
  {
    id: 125,
    question: "Organization policy management enables you to:",
    choices: [
      "Control Copilot feature availability",
      "Change IDE font size",
      "Delete GitHub issues",
      "Disable testing frameworks",
    ],
    answerIndex: 0,
    explanation: "Policies control Copilot feature availability.",
  },
  {
    id: 126,
    question: "Audit logs are useful for:",
    choices: [
      "Tracking organizational events and usage",
      "Improving IDE themes",
      "Increasing suggestion length",
      "Replacing code review",
    ],
    answerIndex: 0,
    explanation: "Audit logs track activity for governance.",
  },
  {
    id: 127,
    question: "Troubleshooting Copilot often starts with:",
    choices: [
      "Checking subscription status and sign-in",
      "Deleting project files",
      "Disabling network",
      "Clearing git history",
    ],
    answerIndex: 0,
    explanation: "Verify subscription and sign-in status first.",
  },
  {
    id: 128,
    question: "If Copilot suggestions stop appearing, check:",
    choices: [
      "Extension status and network connectivity",
      "Monitor brightness",
      "Window placement",
      "Keyboard layout only",
    ],
    answerIndex: 0,
    explanation: "Extensions and network connectivity are common causes.",
  },
  {
    id: 129,
    question: "If a feature is disabled by policy, you should:",
    choices: [
      "Ask an admin to review settings",
      "Bypass the policy",
      "Disable all policies",
      "Use a personal account on company devices",
    ],
    answerIndex: 0,
    explanation: "Policies are managed by admins and should be followed.",
  },
  {
    id: 130,
    question: "Enterprise plans are commonly associated with:",
    choices: [
      "Enhanced organizational controls",
      "No management features",
      "Only personal use",
      "No support",
    ],
    answerIndex: 0,
    explanation: "Enterprise plans focus on organization-wide controls.",
  },
  {
    id: 131,
    question: "Copilot Business is intended for:",
    choices: [
      "Organizations needing management controls",
      "Only individual hobby projects",
      "Offline-only usage",
      "Operating system updates",
    ],
    answerIndex: 0,
    explanation: "Business targets organizations with management needs.",
  },
  {
    id: 132,
    question: "Copilot Individuals is intended for:",
    choices: [
      "Personal use by individual developers",
      "Only large enterprises",
      "Operating system administration",
      "Hardware diagnostics",
    ],
    answerIndex: 0,
    explanation: "Individuals is designed for personal use.",
  },
  {
    id: 133,
    question: "Organization settings can:",
    choices: [
      "Enable or disable Copilot features",
      "Change operating system permissions",
      "Delete repositories automatically",
      "Modify git history",
    ],
    answerIndex: 0,
    explanation: "Settings control which Copilot features are available.",
  },
  {
    id: 134,
    question: "If a file is excluded, Copilot should:",
    choices: [
      "Avoid using it for suggestions",
      "Always suggest from it",
      "Delete it",
      "Move it to a new repo",
    ],
    answerIndex: 0,
    explanation: "Excluded files are not used to generate suggestions.",
  },
  {
    id: 135,
    question: "Exclusions are especially useful for:",
    choices: [
      "Sensitive or regulated data",
      "Public documentation only",
      "Increasing suggestion length",
      "Improving font rendering",
    ],
    answerIndex: 0,
    explanation: "Use exclusions to protect sensitive content.",
  },
  {
    id: 136,
    question: "Duplication detection may:",
    choices: [
      "Flag suggestions similar to public code",
      "Disable linting",
      "Remove tests",
      "Prevent builds",
    ],
    answerIndex: 0,
    explanation: "It can flag suggestions similar to public code.",
  },
  {
    id: 137,
    question: "Policy management helps enforce:",
    choices: [
      "Responsible AI usage and feature controls",
      "Only syntax highlighting",
      "Theme selection",
      "Hardware upgrades",
    ],
    answerIndex: 0,
    explanation: "Policies help enforce responsible use and controls.",
  },
  {
    id: 138,
    question: "A customization discussed in the course is:",
    choices: [
      "Managing content exclusions",
      "Overclocking GPUs",
      "Changing BIOS settings",
      "Editing system kernel",
    ],
    answerIndex: 0,
    explanation: "Content exclusions are a key customization.",
  },
  {
    id: 139,
    question: "A common sign-in issue can be solved by:",
    choices: [
      "Reauthenticating the GitHub account",
      "Deleting source code",
      "Disabling the extension",
      "Changing repository ownership",
    ],
    answerIndex: 0,
    explanation: "Reauthenticating often resolves sign-in issues.",
  },
  {
    id: 140,
    question: "Troubleshooting should respect:",
    choices: [
      "Organization policies and security requirements",
      "Only developer convenience",
      "Removing policy controls",
      "Avoiding any admin contact",
    ],
    answerIndex: 0,
    explanation: "Troubleshooting should comply with policies.",
  },
  {
    id: 141,
    question: "Copilot Agent Mode is designed for:",
    choices: [
      "Autonomous, multi-step development assistance",
      "Only inline autocompletion",
      "Managing hardware devices",
      "Replacing issue trackers",
    ],
    answerIndex: 0,
    explanation: "Agent Mode helps with multi-step tasks autonomously.",
  },
  {
    id: 142,
    question: "A key benefit of Agent Mode is:",
    choices: [
      "Handling multi-file changes with guidance",
      "Avoiding any review",
      "Disabling tests",
      "Skipping validation",
    ],
    answerIndex: 0,
    explanation: "Agent Mode can manage multi-file changes with guidance.",
  },
  {
    id: 143,
    question: "Agent Mode should be used with:",
    choices: [
      "Review and validation of changes",
      "Automatic merging",
      "No oversight",
      "No tests",
    ],
    answerIndex: 0,
    explanation: "Agent outputs must be reviewed and validated.",
  },
  {
    id: 144,
    question: "Copilot coding agent focuses on:",
    choices: [
      "Assigning tasks and automating development work",
      "Replacing GitHub Issues",
      "Managing user accounts",
      "Running production servers",
    ],
    answerIndex: 0,
    explanation: "The coding agent is used to assign and automate tasks.",
  },
  {
    id: 145,
    question: "Responsible use of the coding agent requires:",
    choices: [
      "Validation and review of its outputs",
      "Skipping reviews for speed",
      "Automatic deployment",
      "Disabling security checks",
    ],
    answerIndex: 0,
    explanation: "Outputs still need validation and review.",
  },
  {
    id: 146,
    question: "A coding agent task can be:",
    choices: [
      "Tracked and troubleshot",
      "Hidden with no visibility",
      "Auto-deployed without review",
      "Executed without context",
    ],
    answerIndex: 0,
    explanation: "Tasks can be assigned, tracked, and troubleshot.",
  },
  {
    id: 147,
    question: "Customizing the coding agent can involve:",
    choices: [
      "Extending or validating its behavior",
      "Changing the OS kernel",
      "Removing all tests",
      "Disabling GitHub",
    ],
    answerIndex: 0,
    explanation: "Customization includes extending and validating behavior.",
  },
  {
    id: 148,
    question: "The GitHub MCP Server is described as:",
    choices: [
      "A secure way to integrate GitHub features into AI tools",
      "A local-only linter",
      "A package manager",
      "A database server",
    ],
    answerIndex: 0,
    explanation: "MCP Server integrates GitHub features into AI tools.",
  },
  {
    id: 149,
    question: "MCP Server configuration is covered in:",
    choices: [
      "VS Code setup and Copilot Chat integration",
      "Operating system updates",
      "Git history cleanup",
      "Hardware diagnostics",
    ],
    answerIndex: 0,
    explanation: "The module covers configuring MCP Server in VS Code.",
  },
  {
    id: 150,
    question: "Using MCP Server with Copilot Chat enables:",
    choices: [
      "Secure access to GitHub features through Chat",
      "Replacing all IDE features",
      "Disabling GitHub authentication",
      "Running system updates",
    ],
    answerIndex: 0,
    explanation: "MCP enables secure integration with GitHub features in Chat.",
  },
  {
    id: 151,
    question: "Copilot Spaces are useful for:",
    choices: [
      "Grounded responses with shared context",
      "Replacing documentation",
      "Disabling reviews",
      "Only running tests",
    ],
    answerIndex: 0,
    explanation: "Spaces provide shared, curated context for grounded responses.",
  },
  {
    id: 152,
    question: "Spaces can improve response quality by:",
    choices: [
      "Using curated repositories and docs",
      "Removing context",
      "Avoiding governance",
      "Disabling chat",
    ],
    answerIndex: 0,
    explanation: "Curated context improves response quality.",
  },
  {
    id: 153,
    question: "Copilot-assisted code review helps by:",
    choices: [
      "Catching issues earlier and speeding reviews",
      "Replacing all human reviewers",
      "Disabling tests",
      "Removing best practices",
    ],
    answerIndex: 0,
    explanation: "Copilot can accelerate reviews and catch issues earlier.",
  },
  {
    id: 154,
    question: "Copilot can be used as a reviewer on:",
    choices: ["GitHub.com", "Only local IDE", "Only terminal", "Only email"],
    answerIndex: 0,
    explanation: "Copilot review features are available on GitHub.com.",
  },
  {
    id: 155,
    question: "Automated review should be:",
    choices: [
      "Combined with human review",
      "A complete replacement for humans",
      "Used without any tests",
      "Ignored entirely",
    ],
    answerIndex: 0,
    explanation: "Human review is still required for quality and safety.",
  },
  {
    id: 156,
    question: "Measuring impact of review automation helps to:",
    choices: [
      "Optimize usage and workflow outcomes",
      "Disable Copilot permanently",
      "Increase build times",
      "Avoid improvements",
    ],
    answerIndex: 0,
    explanation: "Measurement helps optimize outcomes and usage.",
  },
  {
    id: 157,
    question: "Review standards can be improved by:",
    choices: [
      "Providing clear guidelines and instructions",
      "Avoiding any standards",
      "Skipping validation",
      "Disabling code review",
    ],
    answerIndex: 0,
    explanation: "Clear guidelines align reviews with team standards.",
  },
  {
    id: 158,
    question: "Copilot review should be paired with:",
    choices: [
      "Testing and manual verification",
      "Skipping all tests",
      "Removing documentation",
      "Only manual approvals",
    ],
    answerIndex: 0,
    explanation: "Testing and verification are still required.",
  },
  {
    id: 159,
    question: "Agent sessions help by:",
    choices: [
      "Managing context for multi-step tasks",
      "Disabling code completion",
      "Removing chat history",
      "Preventing edits",
    ],
    answerIndex: 0,
    explanation: "Agent sessions manage context for longer tasks.",
  },
  {
    id: 160,
    question: "Delegating tasks to sub-agents allows you to:",
    choices: [
      "Split work and manage context effectively",
      "Avoid any review",
      "Disable testing",
      "Remove documentation",
    ],
    answerIndex: 0,
    explanation: "Sub-agents can handle parallel tasks with scoped context.",
  },
  {
    id: 161,
    question: "Copilot improves productivity by:",
    choices: [
      "Reducing time spent on boilerplate",
      "Removing the need for tests",
      "Eliminating code reviews",
      "Replacing Git",
    ],
    answerIndex: 0,
    explanation: "Copilot accelerates coding by generating boilerplate.",
  },
  {
    id: 162,
    question: "Copilot can assist documentation by:",
    choices: [
      "Generating docstrings and comments",
      "Deleting markdown",
      "Replacing issue trackers",
      "Managing releases",
    ],
    answerIndex: 0,
    explanation: "Copilot can generate docstrings and comments.",
  },
  {
    id: 163,
    question: "Reduced context switching means:",
    choices: [
      "Staying in the IDE for answers and suggestions",
      "Avoiding all documentation",
      "Skipping tests",
      "Disabling linting",
    ],
    answerIndex: 0,
    explanation: "Copilot provides help within the IDE context.",
  },
  {
    id: 164,
    question: "Modernizing legacy code often involves:",
    choices: [
      "Updating patterns and APIs",
      "Deleting all history",
      "Avoiding tests",
      "Disabling CI",
    ],
    answerIndex: 0,
    explanation: "Modernization updates patterns and APIs.",
  },
  {
    id: 165,
    question: "Copilot can help developers learn by:",
    choices: [
      "Providing examples and explanations",
      "Replacing all training",
      "Avoiding questions",
      "Removing documentation",
    ],
    answerIndex: 0,
    explanation: "Copilot offers examples and explanations to support learning.",
  },
  {
    id: 166,
    question: "Generating sample data is useful for:",
    choices: [
      "Testing and demos",
      "Replacing production databases",
      "Skipping validation",
      "Changing git history",
    ],
    answerIndex: 0,
    explanation: "Sample data helps with testing and demos.",
  },
  {
    id: 167,
    question: "Refactoring assistance includes:",
    choices: [
      "Improving readability and structure",
      "Deleting documentation",
      "Avoiding code reviews",
      "Changing repository ownership",
    ],
    answerIndex: 0,
    explanation: "Copilot can suggest readability and structure improvements.",
  },
  {
    id: 168,
    question: "Performance suggestions should be:",
    choices: [
      "Validated with profiling",
      "Accepted without review",
      "Used to remove tests",
      "Applied only to UI files",
    ],
    answerIndex: 0,
    explanation: "Profiling validates performance improvements.",
  },
  {
    id: 169,
    question: "Security suggestions should be:",
    choices: [
      "Reviewed with security practices",
      "Accepted blindly",
      "Used to skip scanning",
      "Ignored",
    ],
    answerIndex: 0,
    explanation: "Security changes should be reviewed carefully.",
  },
  {
    id: 170,
    question: "Copilot can help create unit tests by:",
    choices: [
      "Suggesting test cases and structure",
      "Executing tests automatically",
      "Replacing test frameworks",
      "Deleting failing tests",
    ],
    answerIndex: 0,
    explanation: "It suggests test cases and structure.",
  },
  {
    id: 171,
    question: "AI in the SDLC can be used for:",
    choices: [
      "Design, coding, testing, and documentation",
      "Only deployment",
      "Only UI themes",
      "Only license scanning",
    ],
    answerIndex: 0,
    explanation: "AI can assist across multiple SDLC stages.",
  },
  {
    id: 172,
    question: "Aligning with developer preferences means:",
    choices: [
      "Adapting Copilot usage to team workflows",
      "Forcing a single workflow for everyone",
      "Removing options",
      "Disabling configuration",
    ],
    answerIndex: 0,
    explanation: "Teams can align Copilot usage to their workflows.",
  },
  {
    id: 173,
    question: "A key limitation to remember is that Copilot:",
    choices: [
      "May be wrong and needs verification",
      "Always compiles",
      "Always aligns with policy",
      "Never needs review",
    ],
    answerIndex: 0,
    explanation: "Copilot output must be verified.",
  },
  {
    id: 174,
    question: "Measuring Copilot impact can include:",
    choices: [
      "Cycle time and code quality indicators",
      "Only number of commits",
      "IDE theme usage",
      "File size only",
    ],
    answerIndex: 0,
    explanation: "Impact can be measured with productivity and quality metrics.",
  },
  {
    id: 175,
    question: "Copilot can explain unfamiliar code by:",
    choices: [
      "Summarizing its behavior",
      "Executing it in production",
      "Replacing all logic",
      "Deleting files",
    ],
    answerIndex: 0,
    explanation: "Copilot can summarize and explain code behavior.",
  },
  {
    id: 176,
    question: "Boilerplate generation helps by:",
    choices: [
      "Reducing repetitive coding",
      "Removing validation",
      "Replacing tests",
      "Increasing manual work",
    ],
    answerIndex: 0,
    explanation: "Boilerplate generation saves time on repetitive tasks.",
  },
  {
    id: 177,
    question: "Copilot can propose error handling by:",
    choices: [
      "Suggesting try/catch blocks or guard clauses",
      "Removing error handling",
      "Ignoring errors",
      "Disabling logging",
    ],
    answerIndex: 0,
    explanation: "It can suggest try/catch or guard clause patterns.",
  },
  {
    id: 178,
    question: "For migrations, Copilot can help by:",
    choices: [
      "Drafting scripts that you then review",
      "Running migrations automatically in prod",
      "Deleting schemas",
      "Skipping verification",
    ],
    answerIndex: 0,
    explanation: "Copilot can draft scripts, but you must review them.",
  },
  {
    id: 179,
    question: "Reducing repetitive tasks can improve:",
    choices: [
      "Developer productivity",
      "Hardware capacity",
      "Licensing complexity",
      "Server uptime",
    ],
    answerIndex: 0,
    explanation: "Automating repetitive tasks boosts productivity.",
  },
  {
    id: 180,
    question: "Copilot can generate summaries to:",
    choices: [
      "Speed understanding of changes or code",
      "Replace git history",
      "Change repository ownership",
      "Remove documentation",
    ],
    answerIndex: 0,
    explanation: "Summaries help speed understanding.",
  },
  {
    id: 181,
    question: "A repository should be excluded when it contains:",
    choices: [
      "Sensitive or regulated information",
      "General documentation only",
      "Only open source dependencies",
      "Only sample data",
    ],
    answerIndex: 0,
    explanation: "Exclude repos with sensitive or regulated data.",
  },
  {
    id: 182,
    question: "When prompts include proprietary code, you should:",
    choices: [
      "Follow organization policy and minimize exposure",
      "Share as much as possible",
      "Post it publicly",
      "Ignore policy",
    ],
    answerIndex: 0,
    explanation: "Follow policy and minimize exposure of sensitive content.",
  },
  {
    id: 183,
    question: "If Chat suggests insecure code, you should:",
    choices: [
      "Add constraints and request a secure alternative",
      "Accept it unchanged",
      "Skip review",
      "Disable all security checks",
    ],
    answerIndex: 0,
    explanation: "Ask for a secure alternative and validate it.",
  },
  {
    id: 184,
    question: "Few-shot examples are useful to:",
    choices: [
      "Align output style and structure",
      "Remove context",
      "Guarantee correctness without review",
      "Avoid any constraints",
    ],
    answerIndex: 0,
    explanation: "Examples guide style and structure.",
  },
  {
    id: 185,
    question: "Using consistent naming in prompts helps:",
    choices: [
      "Improve alignment with existing code",
      "Reduce clarity",
      "Eliminate context",
      "Avoid tests",
    ],
    answerIndex: 0,
    explanation: "Consistent naming improves alignment with existing code.",
  },
  {
    id: 186,
    question: "After accepting Copilot changes, you should:",
    choices: [
      "Run tests and review the diff",
      "Skip validation",
      "Push directly to production",
      "Disable linting",
    ],
    answerIndex: 0,
    explanation: "Review and test changes after accepting suggestions.",
  },
  {
    id: 187,
    question: "When using Copilot CLI, it is important to:",
    choices: [
      "Review commands before running them",
      "Run commands automatically without review",
      "Disable shell history",
      "Skip confirmations",
    ],
    answerIndex: 0,
    explanation: "Always review suggested commands before execution.",
  },
  {
    id: 188,
    question: "A licensing-safe practice is to:",
    choices: [
      "Review output for compliance and avoid copying blindly",
      "Assume all suggestions are safe",
      "Skip code review",
      "Ignore attribution requirements",
    ],
    answerIndex: 0,
    explanation: "Review suggestions for compliance before use.",
  },
  {
    id: 189,
    question: "Copilot can support brainstorming by:",
    choices: [
      "Proposing multiple approaches to a problem",
      "Replacing final decisions",
      "Removing stakeholder review",
      "Disabling tests",
    ],
    answerIndex: 0,
    explanation: "Copilot can propose multiple approaches for consideration.",
  },
  {
    id: 190,
    question: "Inclusiveness as a responsible AI principle means:",
    choices: [
      "Designing AI that supports diverse users",
      "Optimizing only for speed",
      "Avoiding documentation",
      "Disabling accessibility",
    ],
    answerIndex: 0,
    explanation: "Inclusiveness supports diverse users and accessibility.",
  },
  {
    id: 191,
    question: "Transparency in responsible AI means:",
    choices: [
      "Being clear about AI involvement and limitations",
      "Hiding AI usage",
      "Avoiding documentation",
      "Removing audit logs",
    ],
    answerIndex: 0,
    explanation: "Transparency means disclosing AI use and limitations.",
  },
  {
    id: 192,
    question: "Accountability in responsible AI means:",
    choices: [
      "Humans remain responsible for outcomes",
      "The model is responsible for errors",
      "No review is needed",
      "Policies are optional",
    ],
    answerIndex: 0,
    explanation: "Humans remain accountable for AI-assisted outputs.",
  },
  {
    id: 193,
    question: "Reliability and safety emphasizes:",
    choices: [
      "Consistent and safe performance",
      "Only speed",
      "Avoiding tests",
      "Skipping reviews",
    ],
    answerIndex: 0,
    explanation: "Reliability and safety ensure consistent, safe behavior.",
  },
  {
    id: 194,
    question: "Privacy and security emphasizes:",
    choices: [
      "Protecting sensitive data and access",
      "Sharing secrets broadly",
      "Avoiding encryption",
      "Disabling policies",
    ],
    answerIndex: 0,
    explanation: "Privacy and security protect sensitive data.",
  },
  {
    id: 195,
    question: "Fairness emphasizes:",
    choices: [
      "Avoiding biased outcomes",
      "Only speed",
      "Disabling documentation",
      "Removing governance",
    ],
    answerIndex: 0,
    explanation: "Fairness means avoiding biased outcomes.",
  },
  {
    id: 196,
    question: "Which statement about Copilot suggestions is true?",
    choices: [
      "You can accept or reject them at your discretion",
      "They must always be accepted",
      "They are automatically committed",
      "They replace your IDE",
    ],
    answerIndex: 0,
    explanation: "You control which suggestions to accept.",
  },
  {
    id: 197,
    question: "Providing more relevant context usually results in:",
    choices: [
      "Better aligned suggestions",
      "Less accurate suggestions",
      "No change",
      "Disabled suggestions",
    ],
    answerIndex: 0,
    explanation: "Relevant context improves alignment.",
  },
  {
    id: 198,
    question: "Copilot Chat can be used to:",
    choices: [
      "Explain code and propose changes",
      "Edit git history",
      "Manage system updates",
      "Delete repositories",
    ],
    answerIndex: 0,
    explanation: "Chat can explain code and propose changes.",
  },
  {
    id: 199,
    question: "Which action best supports responsible AI use?",
    choices: [
      "Verify outputs and follow policy",
      "Accept suggestions without review",
      "Avoid tests",
      "Share secrets for better results",
    ],
    answerIndex: 0,
    explanation: "Verification and policy compliance are essential.",
  },
  {
    id: 200,
    question: "Copilot can help with onboarding by:",
    choices: [
      "Explaining project code and patterns",
      "Replacing documentation",
      "Skipping reviews",
      "Disabling tests",
    ],
    answerIndex: 0,
    explanation: "Copilot can explain code and project patterns for newcomers.",
  },
  {
    id: 201,
    question: "Which module introduces Copilot Spaces?",
    choices: [
      "Introduction to Copilot Spaces",
      "Responsible AI with GitHub Copilot",
      "Using GitHub Copilot with Python",
      "Building applications with GitHub Copilot agent mode",
    ],
    answerIndex: 0,
    explanation: "The learning path includes a module on Copilot Spaces.",
  },
  {
    id: 202,
    question: "Which module focuses on responsible AI principles?",
    choices: [
      "Responsible AI with GitHub Copilot",
      "Introduction to Copilot Spaces",
      "Using GitHub Copilot with JavaScript",
      "Leveling up code reviews and pull requests with GitHub Copilot",
    ],
    answerIndex: 0,
    explanation: "Responsible AI is covered in its dedicated module.",
  },
  {
    id: 203,
    question: "Which module covers prompt engineering foundations?",
    choices: [
      "Introduction to prompt engineering with GitHub Copilot",
      "Develop unit tests using GitHub Copilot tools",
      "Using GitHub Copilot with Python",
      "GitHub Copilot Across Environments",
    ],
    answerIndex: 0,
    explanation: "Prompt engineering is covered in its dedicated module.",
  },
  {
    id: 204,
    question: "Which module focuses on generating unit tests with Copilot?",
    choices: [
      "Develop unit tests using GitHub Copilot tools",
      "Introduction to Copilot Spaces",
      "Management and customization considerations with GitHub Copilot",
      "Using GitHub Copilot with JavaScript",
    ],
    answerIndex: 0,
    explanation: "Unit test creation with Copilot is covered in that module.",
  },
  {
    id: 205,
    question: "Copilot for the Command Line is discussed in:",
    choices: [
      "GitHub Copilot Across Environments",
      "Responsible AI with GitHub Copilot",
      "Using GitHub Copilot with Python",
      "Introduction to Copilot Spaces",
    ],
    answerIndex: 0,
    explanation: "The across environments module includes CLI coverage.",
  },
  {
    id: 206,
    question: "Which step occurs before a model returns a suggestion?",
    choices: [
      "Copilot builds a prompt from context",
      "Copilot publishes a release",
      "Copilot deletes outdated files",
      "Copilot changes git history",
    ],
    answerIndex: 0,
    explanation: "Copilot builds a prompt from context before requesting completion.",
  },
  {
    id: 207,
    question: "Use few-shot prompting when you need to:",
    choices: [
      "Show examples to guide style and format",
      "Avoid any examples",
      "Remove all constraints",
      "Hide expected outputs",
    ],
    answerIndex: 0,
    explanation: "Few-shot prompts include examples to guide output.",
  },
  {
    id: 208,
    question: "If a suggestion lacks error handling, you should:",
    choices: [
      "Request error handling or add it yourself",
      "Accept it without changes",
      "Disable tests",
      "Remove validations",
    ],
    answerIndex: 0,
    explanation: "Add or request error handling and validate it.",
  },
  {
    id: 209,
    question: "A benefit of Copilot-assisted review is:",
    choices: [
      "Faster feedback cycles with additional issue detection",
      "Eliminating human review entirely",
      "Avoiding test execution",
      "Replacing security scans",
    ],
    answerIndex: 0,
    explanation: "Copilot can speed feedback cycles and catch issues.",
  },
  {
    id: 210,
    question: "To support IP compliance, you should:",
    choices: [
      "Review outputs and avoid copying blindly",
      "Assume all outputs are compliant",
      "Skip code review",
      "Ignore licensing requirements",
    ],
    answerIndex: 0,
    explanation: "Always review output for licensing and compliance.",
  },
  {
    id: 211,
    question:
      "A team needs centralized policy controls and audit logs for Copilot. Which plan best fits?",
    choices: ["Individual", "Business", "Enterprise", "Any plan is identical"],
    answerIndex: 2,
    explanation: "Enterprise plans offer the most advanced org controls and auditability.",
  },
  {
    id: 212,
    question:
      "Which setup is required to use Copilot Chat inside your IDE?",
    choices: [
      "Install the Copilot extension and sign in",
      "Enable GitHub Pages",
      "Create a new repository",
      "Disable inline suggestions",
    ],
    answerIndex: 0,
    explanation: "Copilot Chat in IDEs requires the extension and authentication.",
  },
  {
    id: 213,
    question:
      "Your organization wants to prevent Copilot from using a folder with secrets. What should you configure?",
    choices: [
      "Content exclusions for that folder",
      "Disable linting",
      "Rename the folder",
      "Move the folder to a different branch",
    ],
    answerIndex: 0,
    explanation: "Content exclusions prevent specific files or paths from being used.",
  },
  {
    id: 214,
    question:
      "A developer asks Copilot for a command. What is the safest practice?",
    choices: [
      "Run the command immediately",
      "Review the command before executing",
      "Disable shell history",
      "Use root privileges by default",
    ],
    answerIndex: 1,
    explanation: "Commands generated by AI should be reviewed before running.",
  },
  {
    id: 215,
    question:
      "Copilot suggestions are produced after the model receives:",
    choices: [
      "A prompt built from surrounding context",
      "Only the file name",
      "Only your commit history",
      "A compiled binary",
    ],
    answerIndex: 0,
    explanation: "Copilot builds a prompt from nearby code, comments, and context.",
  },
  {
    id: 216,
    question:
      "You need to explain a complex function to a teammate. Which Copilot feature is most appropriate?",
    choices: [
      "Copilot Chat in the IDE",
      "Copilot CLI only",
      "Disable completions",
      "Only inline suggestions",
    ],
    answerIndex: 0,
    explanation: "Copilot Chat can summarize and explain code behavior.",
  },
  {
    id: 217,
    question:
      "Which scenario best fits using Copilot for refactoring?",
    choices: [
      "Improving readability and structure while preserving behavior",
      "Automatically deleting unused files",
      "Changing git history",
      "Disabling tests",
    ],
    answerIndex: 0,
    explanation: "Refactoring focuses on structure and clarity without changing behavior.",
  },
  {
    id: 218,
    question:
      "A user wants to avoid public-code-like suggestions. Which setting helps?",
    choices: [
      "Disable matching public code",
      "Enable auto-accept",
      "Turn off content exclusions",
      "Disable code review",
    ],
    answerIndex: 0,
    explanation: "Disabling matching public code reduces similar suggestions.",
  },
  {
    id: 219,
    question:
      "Which example best reflects zero-shot prompting?",
    choices: [
      "Provide instructions with no examples",
      "Provide three example inputs/outputs",
      "Copy a full solution for the model",
      "Use only commit messages",
    ],
    answerIndex: 0,
    explanation: "Zero-shot prompts use instructions without examples.",
  },
  {
    id: 220,
    question:
      "A team wants to limit Copilot to organization-approved repositories. What should they use?",
    choices: [
      "Organization policies and content exclusions",
      "Local git hooks only",
      "A single developer account",
      "Disabling all IDE extensions",
    ],
    answerIndex: 0,
    explanation: "Org policies and exclusions control repo access and usage.",
  },
  {
    id: 221,
    question:
      "Which action best validates a Copilot-generated unit test?",
    choices: [
      "Run the test and review assertions",
      "Assume it is correct",
      "Skip edge cases",
      "Remove assertions to reduce failures",
    ],
    answerIndex: 0,
    explanation: "Tests must be executed and reviewed for correctness.",
  },
  {
    id: 222,
    question:
      "A developer shares proprietary code in a prompt. What is the best response?",
    choices: [
      "Minimize exposure and follow policy",
      "Share more to improve accuracy",
      "Post it in a public issue",
      "Ignore policy for speed",
    ],
    answerIndex: 0,
    explanation: "Follow policy and minimize exposure of sensitive content.",
  },
  {
    id: 223,
    question:
      "Which workflow best uses Copilot to improve productivity?",
    choices: [
      "Generate boilerplate, then review and test",
      "Accept all suggestions automatically",
      "Disable tests to save time",
      "Avoid documentation entirely",
    ],
    answerIndex: 0,
    explanation: "Copilot is effective when paired with review and testing.",
  },
  {
    id: 224,
    question:
      "A teammate asks how Copilot handles context. What is accurate?",
    choices: [
      "It uses surrounding code and relevant files to build a prompt",
      "It only reads your entire repository",
      "It uses only commit history",
      "It ignores open files",
    ],
    answerIndex: 0,
    explanation: "Copilot builds prompts from nearby context and related files.",
  },
  {
    id: 225,
    question:
      "You need help writing documentation for a new API. Which use case fits?",
    choices: [
      "Copilot can draft docstrings and summaries",
      "Copilot should replace API review",
      "Copilot can publish docs automatically",
      "Copilot should skip explanations",
    ],
    answerIndex: 0,
    explanation: "Copilot can help draft documentation, which you then review.",
  },
  {
    id: 226,
    question:
      "Which scenario is most appropriate for Copilot CLI?",
    choices: [
      "Generate a shell command from a natural language request",
      "Edit git history",
      "Enable repository policies",
      "Configure IDE themes",
    ],
    answerIndex: 0,
    explanation: "Copilot CLI converts natural language to commands.",
  },
  {
    id: 227,
    question:
      "A regulated project requires strict governance. Which plan aligns best?",
    choices: ["Individual", "Business", "Enterprise", "Any plan is identical"],
    answerIndex: 2,
    explanation: "Enterprise provides the strongest governance and controls.",
  },
  {
    id: 228,
    question:
      "What is the safest approach when Copilot suggests a security change?",
    choices: [
      "Review and validate with security practices",
      "Accept without review",
      "Disable security scanning",
      "Ignore the suggestion",
    ],
    answerIndex: 0,
    explanation: "Security changes must be reviewed and validated.",
  },
  {
    id: 229,
    question:
      "Which best describes how Copilot handles data and prompts?",
    choices: [
      "It collects context, builds a prompt, then receives completions",
      "It trains a new model on your repo by default",
      "It ignores open files",
      "It only uses issue titles",
    ],
    answerIndex: 0,
    explanation: "Copilot uses context to build a prompt and request completions.",
  },
  {
    id: 230,
    question:
      "A team wants Copilot in GitHub.com pull request review. Where is this available?",
    choices: ["GitHub.com", "Only local IDEs", "Only terminal", "Email only"],
    answerIndex: 0,
    explanation: "Copilot review features are available on GitHub.com.",
  },
  {
    id: 231,
    question:
      "Which prompt is most likely to yield a useful refactor?",
    choices: [
      "Refactor this function to improve readability while preserving behavior",
      "Make it better",
      "Do whatever you want",
      "Refactor without constraints",
    ],
    answerIndex: 0,
    explanation: "Clear goals and constraints produce better refactoring results.",
  },
  {
    id: 232,
    question:
      "A developer should choose Business over Individual when:",
    choices: [
      "They need org-level management and policy controls",
      "They only work on a personal project",
      "They never use IDEs",
      "They want to disable authentication",
    ],
    answerIndex: 0,
    explanation: "Business plans support organization management controls.",
  },
  {
    id: 233,
    question:
      "What is a recommended step when Copilot responses seem inaccurate?",
    choices: [
      "Ask a clarifying follow-up prompt and verify",
      "Assume it is correct",
      "Disable code review",
      "Copy the output directly to production",
    ],
    answerIndex: 0,
    explanation: "Iterative prompting and validation improve accuracy.",
  },
  {
    id: 234,
    question:
      "Which choice best protects privacy when using Copilot Chat?",
    choices: [
      "Avoid sharing secrets and follow content exclusions",
      "Paste credentials for faster results",
      "Post secrets in comments for context",
      "Disable review processes",
    ],
    answerIndex: 0,
    explanation: "Do not share secrets and use exclusions to protect sensitive data.",
  },
  {
    id: 235,
    question:
      "An organization requires SSO and centralized user management for Copilot. Which plan aligns best?",
    choices: ["Individual", "Business", "Enterprise", "Any plan is the same"],
    answerIndex: 2,
    explanation: "Enterprise plans are designed for advanced org controls and SSO.",
  },
  {
    id: 236,
    question:
      "A developer wants Copilot in the terminal for quick command drafts. Which tool should they use?",
    choices: ["Copilot CLI", "Copilot Chat only", "GitHub Actions", "Dependabot"],
    answerIndex: 0,
    explanation: "Copilot CLI turns natural language into shell commands.",
  },
  {
    id: 237,
    question:
      "Your team needs to restrict Copilot usage to approved repositories only. What is the right control?",
    choices: [
      "Organization policy settings",
      "Local editor theme",
      "Git hooks only",
      "A private README",
    ],
    answerIndex: 0,
    explanation: "Org policies control feature access and repository scope.",
  },
  {
    id: 238,
    question:
      "Which is a correct statement about Copilot data flow?",
    choices: [
      "Context is gathered and used to build a prompt for completions",
      "The model trains on your repository by default",
      "Copilot ignores the current file",
      "Only the file name is used",
    ],
    answerIndex: 0,
    explanation: "Copilot builds a prompt from surrounding context and metadata.",
  },
  {
    id: 239,
    question:
      "A developer wants more accurate suggestions. Which practice helps most?",
    choices: [
      "Add clear intent and constraints in comments",
      "Remove all descriptive names",
      "Avoid describing expected outputs",
      "Disable tests",
    ],
    answerIndex: 0,
    explanation: "Clear intent and constraints improve suggestion quality.",
  },
  {
    id: 240,
    question:
      "A team uses Copilot for refactoring. What must they do before merging?",
    choices: [
      "Review changes and run tests",
      "Skip code review",
      "Disable linting",
      "Avoid edge cases",
    ],
    answerIndex: 0,
    explanation: "Refactors still require review and test validation.",
  },
  {
    id: 241,
    question:
      "Which task best fits Copilot Chat on GitHub.com?",
    choices: [
      "Drafting pull request summaries and review comments",
      "Editing git history",
      "Changing repository ownership",
      "Managing DNS records",
    ],
    answerIndex: 0,
    explanation: "Copilot on GitHub.com supports PR assistance.",
  },
  {
    id: 242,
    question:
      "When using Copilot to create tests, which detail is most important to include?",
    choices: [
      "Expected inputs and outputs",
      "Only function name",
      "No context at all",
      "Ignore edge cases",
    ],
    answerIndex: 0,
    explanation: "Inputs and expected outputs guide accurate tests.",
  },
  {
    id: 243,
    question:
      "A suggestion appears to match public code closely. What should you do?",
    choices: [
      "Review for licensing compliance and adjust",
      "Accept immediately",
      "Skip review since it compiles",
      "Disable code review",
    ],
    answerIndex: 0,
    explanation: "Check licensing and compliance before use.",
  },
  {
    id: 244,
    question:
      "Which practice supports privacy when using Copilot in regulated projects?",
    choices: [
      "Apply content exclusions and minimize sensitive context",
      "Paste secrets to improve accuracy",
      "Disable documentation review",
      "Share credentials in prompts",
    ],
    answerIndex: 0,
    explanation: "Use exclusions and avoid sharing sensitive data.",
  },
  {
    id: 245,
    question:
      "Which feature helps reduce context switching for developers?",
    choices: [
      "Copilot Chat in the IDE",
      "Disabling inline suggestions",
      "Only external documentation",
      "Manual command lookups only",
    ],
    answerIndex: 0,
    explanation: "IDE chat keeps help in context.",
  },
  {
    id: 246,
    question:
      "A team wants to ensure Copilot output aligns with security standards. What is required?",
    choices: [
      "Security review and testing of suggestions",
      "Auto-accept suggestions",
      "Disable linters",
      "Skip dependency checks",
    ],
    answerIndex: 0,
    explanation: "Security review and testing are required.",
  },
  {
    id: 247,
    question:
      "Which statement is true about Copilot plan differentiation?",
    choices: [
      "Business and Enterprise include more admin controls than Individual",
      "All plans have identical controls",
      "Individual has the most org features",
      "Plans do not differ in management",
    ],
    answerIndex: 0,
    explanation: "Business/Enterprise provide extra management capabilities.",
  },
  {
    id: 248,
    question:
      "A developer is unsure about a Copilot-generated solution. What should they do?",
    choices: [
      "Verify with docs, tests, or a follow-up prompt",
      "Assume it is correct",
      "Disable code review",
      "Commit immediately",
    ],
    answerIndex: 0,
    explanation: "Validate with trusted sources and tests.",
  },
  {
    id: 249,
    question:
      "Which best describes few-shot prompting?",
    choices: [
      "Provide one or more examples to guide output",
      "Provide no examples at all",
      "Only use commit messages",
      "Avoid constraints",
    ],
    answerIndex: 0,
    explanation: "Few-shot uses examples to shape the response.",
  },
  {
    id: 250,
    question:
      "Which use case best matches Copilot for documentation?",
    choices: [
      "Drafting API summaries and docstrings for review",
      "Replacing documentation owners",
      "Publishing docs automatically",
      "Skipping explanations",
    ],
    answerIndex: 0,
    explanation: "Copilot can draft docs, which you then review.",
  },
  {
    id: 251,
    question:
      "A team needs to audit Copilot usage across the organization. What helps most?",
    choices: [
      "Enterprise plan with audit logs",
      "Individual plan only",
      "Local IDE themes",
      "Disabling policy controls",
    ],
    answerIndex: 0,
    explanation: "Enterprise provides audit and governance features.",
  },
  {
    id: 252,
    question:
      "Which action best reduces risk of hallucinated outputs?",
    choices: [
      "Validate results with tests and review",
      "Accept suggestions without review",
      "Disable linting",
      "Avoid any documentation",
    ],
    answerIndex: 0,
    explanation: "Validation mitigates hallucination risk.",
  },
  {
    id: 253,
    question:
      "Which feature enables Copilot to assist in PR reviews on GitHub.com?",
    choices: [
      "Copilot in GitHub.com",
      "Only IDE inline suggestions",
      "Only CLI",
      "Only local editor settings",
    ],
    answerIndex: 0,
    explanation: "PR assistance is available on GitHub.com.",
  },
  {
    id: 254,
    question:
      "A developer wants to generate a migration script. What should they do?",
    choices: [
      "Use Copilot to draft and then review carefully",
      "Run it in production without review",
      "Disable tests and deploy",
      "Skip validation for speed",
    ],
    answerIndex: 0,
    explanation: "Draft with Copilot but review and validate.",
  },
  {
    id: 255,
    question:
      "Which is the most responsible approach to AI-generated code ownership?",
    choices: [
      "Developers remain responsible for accepted code",
      "The model owns the code",
      "GitHub owns all code",
      "Ownership is transferred automatically",
    ],
    answerIndex: 0,
    explanation: "Developers are accountable for accepted code.",
  },
  {
    id: 256,
    question:
      "A team wants to disable Copilot for specific file patterns. What should they use?",
    choices: [
      "Content exclusions",
      "Disable the repository",
      "Change file extensions",
      "Move files to a new branch only",
    ],
    answerIndex: 0,
    explanation: "Content exclusions can target files or paths.",
  },
  {
    id: 257,
    question:
      "Which behavior best aligns with responsible AI usage?",
    choices: [
      "Review outputs for correctness, bias, and safety",
      "Trust outputs without review",
      "Avoid tests",
      "Bypass policies",
    ],
    answerIndex: 0,
    explanation: "Responsible use requires review and policy adherence.",
  },
  {
    id: 258,
    question:
      "A team wants to measure productivity impact from Copilot. What metric is relevant?",
    choices: [
      "Cycle time and code quality indicators",
      "Only file size",
      "Only commit count",
      "IDE theme usage",
    ],
    answerIndex: 0,
    explanation: "Impact is measured with productivity and quality metrics.",
  },
  {
    id: 259,
    question:
      "Which scenario best uses Copilot for debugging?",
    choices: [
      "Explaining a stack trace and suggesting fixes",
      "Deleting failing tests",
      "Ignoring error logs",
      "Disabling linting",
    ],
    answerIndex: 0,
    explanation: "Copilot can explain errors and propose fixes.",
  },
  {
    id: 260,
    question:
      "Which statement about context exclusions is accurate?",
    choices: [
      "Excluded content is not used to generate suggestions",
      "Excluded content is always prioritized",
      "Exclusions only affect documentation",
      "Exclusions delete files automatically",
    ],
    answerIndex: 0,
    explanation: "Excluded content is ignored for suggestions.",
  },
  {
    id: 261,
    question:
      "Which is a valid reason to choose Business over Individual?",
    choices: [
      "Need for organization billing and controls",
      "Only personal hobby projects",
      "No admin requirements",
      "Offline-only usage",
    ],
    answerIndex: 0,
    explanation: "Business supports org management and billing.",
  },
  {
    id: 262,
    question:
      "Which is a best practice for prompt clarity?",
    choices: [
      "State goal, constraints, and expected output",
      "Use a vague one-liner",
      "Avoid mentioning language",
      "Remove context",
    ],
    answerIndex: 0,
    explanation: "Clear goals and constraints improve responses.",
  },
  {
    id: 263,
    question:
      "A developer wants to avoid misuse of sensitive context. What is the best action?",
    choices: [
      "Exclude sensitive files and avoid sharing secrets",
      "Paste secrets for accuracy",
      "Assume Copilot filters everything",
      "Store secrets in comments",
    ],
    answerIndex: 0,
    explanation: "Use exclusions and avoid sharing secrets.",
  },
  {
    id: 264,
    question:
      "What is a reliable way to evaluate AI-generated refactors?",
    choices: [
      "Run tests and compare behavior",
      "Assume behavior is unchanged",
      "Skip code review",
      "Disable linting",
    ],
    answerIndex: 0,
    explanation: "Tests and review confirm behavior preservation.",
  },
  {
    id: 265,
    question:
      "Which statement is most accurate about AI limitations?",
    choices: [
      "AI can be wrong and needs verification",
      "AI is always correct",
      "AI replaces code review",
      "AI ensures security by default",
    ],
    answerIndex: 0,
    explanation: "AI output must be verified.",
  },
  {
    id: 266,
    question:
      "Your team needs to ensure only approved Copilot features are enabled. What controls this?",
    choices: [
      "Organization policy settings",
      "Local keyboard shortcuts",
      "Theme settings",
      "Commit message templates",
    ],
    answerIndex: 0,
    explanation: "Org policies control feature availability.",
  },
  {
    id: 267,
    question:
      "Which scenario best reflects an effective use case for Copilot in testing?",
    choices: [
      "Generate unit test scaffolding and add edge cases",
      "Remove failing tests",
      "Skip assertions",
      "Avoid test frameworks",
    ],
    answerIndex: 0,
    explanation: "Copilot can generate scaffolding, but tests need validation.",
  },
  {
    id: 268,
    question:
      "A developer wants Copilot to suggest code aligned with team style. What helps most?",
    choices: [
      "Provide examples and constraints in the prompt",
      "Avoid any context",
      "Disable linting rules",
      "Use inconsistent naming",
    ],
    answerIndex: 0,
    explanation: "Examples and constraints align output with style.",
  },
  {
    id: 269,
    question:
      "Which best describes Copilot’s role in the SDLC?",
    choices: [
      "Assists with design, coding, testing, and documentation",
      "Only deploys applications",
      "Only creates UI themes",
      "Only manages licensing",
    ],
    answerIndex: 0,
    explanation: "Copilot can assist across multiple SDLC stages.",
  },
  {
    id: 270,
    question:
      "What should you do when a generated suggestion includes a potential vulnerability?",
    choices: [
      "Reject or revise it and apply secure practices",
      "Accept it for speed",
      "Disable security tools",
      "Ignore it",
    ],
    answerIndex: 0,
    explanation: "Security issues must be addressed before use.",
  },
  {
    id: 271,
    question:
      "Which statement about using Copilot in regulated industries is correct?",
    choices: [
      "Follow policy, minimize sensitive context, and validate outputs",
      "Share secrets to improve accuracy",
      "Ignore organization controls",
      "Skip compliance checks",
    ],
    answerIndex: 0,
    explanation: "Compliance requires policy adherence and validation.",
  },
  {
    id: 272,
    question:
      "Which scenario best uses Copilot for code review assistance?",
    choices: [
      "Summarize changes and flag potential issues",
      "Automatically approve all PRs",
      "Bypass human review",
      "Disable testing",
    ],
    answerIndex: 0,
    explanation: "Copilot can assist but does not replace human review.",
  },
  {
    id: 273,
    question:
      "Which statement is accurate about Copilot Chat context?",
    choices: [
      "Referencing files and code blocks improves relevance",
      "Context never affects responses",
      "Only file names matter",
      "Chat ignores repository context",
    ],
    answerIndex: 0,
    explanation: "Specific context improves response relevance.",
  },
  {
    id: 274,
    question:
      "What is a reliable approach to using Copilot for productivity gains?",
    choices: [
      "Use it for boilerplate, then validate and refine",
      "Accept everything automatically",
      "Disable tests and reviews",
      "Avoid code comments and context",
    ],
    answerIndex: 0,
    explanation: "Productivity gains come with review and validation.",
  },
  {
    id: 275,
    question:
      "Which skill area focuses on configuring content exclusions and safeguards?",
    choices: [
      "Configure privacy, content exclusions, and safeguards",
      "Improve developer productivity with GitHub Copilot",
      "Apply prompt engineering and context crafting",
      "Use GitHub Copilot responsibly",
    ],
    answerIndex: 0,
    explanation: "Privacy, exclusions, and safeguards are a dedicated skill area.",
  },
  {
    id: 276,
    question:
      "Which activity best aligns with understanding Copilot data and architecture?",
    choices: [
      "Explaining how context is collected and prompts are built",
      "Choosing an IDE theme",
      "Renaming repository branches",
      "Publishing a release",
    ],
    answerIndex: 0,
    explanation: "Data flow and prompt construction are core architecture topics.",
  },
  {
    id: 277,
    question:
      "Which prompt practice most directly improves prompt engineering results?",
    choices: [
      "State the goal, constraints, and expected output",
      "Use a vague one-liner",
      "Avoid specifying the language",
      "Remove all context",
    ],
    answerIndex: 0,
    explanation: "Clear goals and constraints improve output quality.",
  },
  {
    id: 278,
    question:
      "Which scenario best reflects responsible Copilot usage?",
    choices: [
      "Review suggestions, validate with tests, and follow policy",
      "Accept all suggestions without review",
      "Share secrets to get better suggestions",
      "Skip security checks for speed",
    ],
    answerIndex: 0,
    explanation: "Responsible usage requires review, testing, and policy adherence.",
  },
  {
    id: 279,
    question:
      "Which is an example of using GitHub Copilot features across environments?",
    choices: [
      "Using Copilot Chat in the IDE and Copilot on GitHub.com",
      "Only using syntax highlighting",
      "Only using local git hooks",
      "Only using a terminal alias",
    ],
    answerIndex: 0,
    explanation: "Copilot features span IDEs, GitHub.com, and the CLI.",
  },
  {
    id: 280,
    question:
      "Which action best demonstrates improving developer productivity with Copilot?",
    choices: [
      "Generate boilerplate code and then review it",
      "Disable tests to reduce cycle time",
      "Avoid documentation entirely",
      "Accept all suggestions automatically",
    ],
    answerIndex: 0,
    explanation: "Copilot can speed work when paired with review and tests.",
  },
  {
    id: 281,
    question:
      "Which option represents a GitHub Copilot feature that supports code review?",
    choices: [
      "Copilot-assisted pull request summaries on GitHub.com",
      "Manual linting only",
      "Disabling review comments",
      "Removing PR templates",
    ],
    answerIndex: 0,
    explanation: "Copilot can assist with PR summaries and review workflows.",
  },
];
